### ISSUE TITLE
erasing data

### ISSUE THREAD

**Issue by ZmeyGorynychh** [jpfranci/fb-messages-visualizer#4]
Hi! It's an old project so I don't know if you still look at this page. 
The tool works really well, but I'm trying to delete the data i imported, in order to import data from the same chat, over a longer time span. I uninstalled ChatStats, reinstalled it, but the grapghs are still here. 
When I import the data with the longer timespan, nothing changes. 
Thanks!

**Comment by jpfranci** [comment]
Hi! I just pushed an update in the windows platform that deletes the database when you uninstall.

I also included a toggle when you load data that gives you the ability to wipe the existing conversation.
![image](https://user-images.githubusercontent.com/42393264/105280327-59686780-5b5e-11eb-9c5a-bb321437cdd2.png)

**Comment by ZmeyGorynychh** [comment]
Hey! That's awesome, works perfectly~
Thanks a lot :)
